import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { SeoMeta } from "@/components/site-layout";
import master from "@/assets/maestro-linaje-bata-blanca.jpeg.asset.json";
import lineage from "@/assets/parampara.jpg.asset.json";
import lia from "@/assets/lia-guru.jpg.asset.json";
export const Route=createFileRoute("/")({head:()=>SeoMeta("Fundación Hariharananda Kriya Yoga","Kriya Yoga, un camino para todos. Fundación en Envigado, Colombia."),component:Home});
function Home(){return <>
<section className="home-hero"><div className="section-x home-hero__inner"><div className="home-hero__copy"><span className="home-hero__rule"/><h1><span>Fundación</span>Hariharananda Kriya Yoga</h1><p className="home-hero__subtitle">Un camino para todos</p><p className="home-hero__lead">El Kriya Yoga es el método más apropiado para el hombre del siglo XXI.</p><div className="home-hero__actions"><Link to="/kriya-yoga">Conocer Kriya Yoga <ArrowRight/></Link><Link to="/contacto" className="outline">Contacto</Link></div></div><figure className="lineage-portrait"><span className="lineage-portrait__plane lineage-portrait__plane--one"/><span className="lineage-portrait__plane lineage-portrait__plane--two"/><div className="lineage-portrait__frame"><img src={master.url} alt="Maestro del linaje de Kriya Yoga con bata blanca"/></div><figcaption>El linaje</figcaption></figure></div></section>
<section className="lineage-band"><div className="section-x"><p>El linaje</p><img src={lineage.url} alt="Parampara: linaje de maestros de Kriya Yoga"/></div></section>
<section className="home-article"><div className="section-x article-wrap"><header><h2>KRIYA YOGA</h2><p>UN CAMINO PARA TODOS</p></header>
<p>En general, hay muchos caminos que buscan ir más allá de las limitaciones de la mente y experimentar la naturaleza del propio ser. En casi todos estos sistemas, el objetivo principal está en la concentración. Tratan de retirar la consciencia de los objetos exteriores y llevarla a los reinos interiores de la mente, a través de la concentración.</p>
<p>Los grandes maestros han proclamado que los seres humanos tienen en sí mismos un enorme potencial, que los hace capaces de experimentar diferentes planos de la consciencia. Sin embargo, una gran parte de la humanidad vive en un plano inferior de existencia, sin ni siquiera darse cuenta de otros planos superiores. El resultado es una vida infeliz e insatisfecha; ignorando que solo un destello de una esfera superior de consciencia aleja toda infelicidad y descontento.</p>
<img className="float-photo" src={lia.url} alt="Yogacharya Lía Cristina Upegui con su Gurú"/>
<p>Pero este no es un proceso fácil. La mente, por naturaleza se mueve todo el tiempo. Cualquier intento de controlarla directa y forzadamente resulta en una reacción chocante. El resultado es tensión y frustración.</p><p>Cuando la mente es incapaz de relajarse, proyecta corrientes de pensamientos a la mente consciente y estos dificultan la concentración en muchas personas. Cuanto más lo intentan, más se tensionan. Por eso es necesario un sistema que progresivamente conduzca a la persona a estados de relajación profunda del cuerpo y la mente, <em>donde la concentración aparece espontáneamente</em>. Este sistema es llamado KRIYA YOGA.</p>
<p>En el KRIYA YOGA se le da más atención a la consciencia. Esto es, atención consciente de los pensamientos u objetos. No se hace ningún intento directo de dirigir la concentración. Se induce la consciencia a hacer ciertos movimientos internos. Nunca hay un intento de suprimir los pensamientos; simplemente se acepta que surjan y desaparezcan; la persona es solo testigo.</p><p>Dado que el KRIYA YOGA no presupone concentración, ni siquiera el retiro de la conciencia del entorno exterior, es el sistema más conveniente para el hombre moderno. Se adapta completamente al estilo de vida de un hombre extrovertido. Practique KRIYA YOGA —sin temor o inseguridad— y encontrará todo lo que estaba buscando.</p>
<p>Uno de los muchos significados para Kriya es actividad o movimiento. Es el movimiento de la consciencia. Otro significado de Kriya es práctica o preliminar; en ese sentido es la práctica preliminar que lleva a la autorealización. El KRIYA YOGA no se opone directamente a las fluctuaciones mentales, aunque logra ese objetivo. De esta manera, sus facultades mentales se armonizan y florecen en todo su potencial.</p><p>El KRIYA YOGA es el método más apropiado para el hombre del siglo XXI. Sin forzar nada, el Kriya yoga domestica la mente y se convierte en una herramienta perfecta para la <em>meditación espontánea</em>. Para un Kriya yogui no se necesita esfuerzo mental para eliminar la tensión y los problemas. La práctica regular del KRIYA YOGA es lo único necesario y, en el curso del tiempo, se alcanza una mente cristalina, sin preocupaciones.</p><p><strong>Cualquier persona</strong> mayor de 12 años, independientemente de su condición, podrá recibir iniciación en esta maravillosa técnica. Todos pueden practicar KRIYA YOGA, sin importar los hábitos alimentarios, la posición social, el nivel de educación, la religión o cualquier otra situación. Todo lo que se requiere es una mente lista para aceptar la práctica sincera y querer <em>ser feliz</em>.</p>
<div className="article-links"><Link to="/documentos">Documentos de la Fundación <ArrowRight/></Link><Link to="/libros">Libros de Kriya Yoga <ArrowRight/></Link></div></div></section></>}
