import { createFileRoute } from "@tanstack/react-router"; import { PageTitle,SeoMeta } from "@/components/site-layout"; import image from "@/assets/kriya-baba.png.asset.json";
export const Route=createFileRoute("/kriya-yoga")({head:()=>SeoMeta("Kriya Yoga — Fundación Hariharananda Kriya Yoga","Enseñanzas de los maestros de Kriya Yoga."),component:Page});
const quotes=[
["El bote de la vida debe estar anclado en la Consciencia Cósmica. Si se ancla el bote al fondo, se puede remar toda la noche, pero ¿adónde llegará? Sri Yukteswar dijo que muchos practican Kriya Yoga así, sin saber el propósito verdadero de la técnica. Se debe primero levar el ancla y buscar al capitán. El bote del cuerpo no puede navegar con su solo poder. Todos sus movimientos vienen del Todopoderoso. Siempre debe anclarse en el Todopoderoso.","P. Hariharananda"],
["Yogiraj elucidó que “la realización se da a través de Kutastha”. Logrando la permanencia en Kutastha, el yogui adquiere el conocimiento verdadero. Ya que es semejante al cielo, se le conoce como la Caverna de la Unión con el Vacío Absoluto. Si se logra la permanencia en esta Caverna, el yogui adquiere conocimiento profundo de las esencias de la religión.","Del libro Puran Purusha"],
["“Mientras se practica este Pranayama, emana un sonido extremadamente melifluo. Solamente este, es el que se conoce como el sonido Pranava. Si se detalla cuidadosamente la flauta que Krishna toca, se observan 6 agujeros. Para explicar el dulce sonido producto de este Pranayama a lo largo del camino de los 6 chakras, se representa el símbolo de Bhagavan Krishna sosteniendo la flauta en sus manos. Esta no es una flauta física. Esta flauta es el símbolo del Pranayama interno a lo largo del cordón espinal a través del medio de los 6 chakras”.","Ashoke Kumar Chatterjee en Who Is This Shama Churn (nieto de Lahiri Mahasaya, autor de Puran Purusha)"],
["“El poder serpenteante (kundalini) es el asiento de la fuerza de vida en la sushumna. Los practicantes de Kriya Yoga experimentan el poder serpenteante (kundalini shakti) como una luz dorada extremadamente brillante. El practicante la experimenta como fuego en el centro muladhara”.","Rajarshi Raghabananda en The Essence of Kriya Yoga"],
["“El Kriya Yoga es una ciencia de la respiración correcta. Al inhalar de forma apropiada, cuando la calma desciende, el devoto permanece en pleno gozo, luz divina y la vibración divina”.","Paramahansa Hariharananda"],
["“Un día el Poder Cósmico ya no respirará por tu nariz y tendrás que dejar inmediatamente todas las propiedades y la prosperidad, el ego y la vanidad, la fortuna y la familia, los amigos y los conocidos, todo (...). Ofrece todo a la Consciencia Cósmica y a los maestros”.","Paramahansa Hariharananda"],
["“Tomando este cuerpo como nuestro laboratorio, podemos realizar una experimentación sistemática y nos podemos dar cuenta del profundo significado y eficacia del Kriya Yoga”.","Baba Hariharananda"],
["En el yogui, la fuerza de vida se mueve en la sushumna. Pero en el hombre ordinario, la sushumna está cerrada. El prana fluye por ida y pingala. La regulación de la respiración en ida y pingala provoca estabilidad en la sushumna. Cuando inhalamos, el nervio ida se activa. Cuando exhalamos, el nervio pingala se activa. El estado de equilibrio de la respiración en la ida y pingala está en la sushumna. Un yogui puede fácilmente mantenerse en la sushumna.","Rajarshi Raghabananda en The essence of Kriya Yoga"],
["Superconsciencia y consciencia cósmica significan que el cuerpo y el alma se perciben como uno. Este es el so-ham, o estado de hamsa, que significa “Yo y Él (el alma) somos uno”; en otras palabras, el alma y la naturaleza del cuerpo son uno. En este estado, los yoguis sienten al ser humano en Dios y a Dios en el ser humano. Ellos constantemente disfrutan de gozo divino, dicha y paz. Ellos sienten al alma funcionando a través de sus cuerpos. Este es el real conocimiento de la yoga.","El maestro Hariharananda en Life and Teachings of Paramahansa Hariharananda, escrito por algunos de sus discípulos"],
["“El estado en el cual el practicante se libera del apego y alcanza la calma y un estado estable de Conciencia de Dios es llamado estado de shambhavi. La mente se funde en el alma profunda. La introversión de la mente es shambhavi mudra”.","Rajarshi Raghabananda en The Essence of Kriya Yoga (pág. 65)"],
["“La mente emerge de la energía vital, el punto de nacimiento de la mente es la respiración”.","Así dice Baba"]] as const;
function Page(){return <div className="section-x interior"><PageTitle>KRIYA YOGA</PageTitle><img className="kriya-image" src={image.url} alt="Baba enseñando Kriya Yoga"/><div className="quotes">{quotes.map(([q,c],i)=><blockquote key={i}><p>{q}</p><cite>{c}</cite></blockquote>)}</div><article className="last-advice"><h2>Mi último consejo — Baba Raghabananda</h2><p className="date">Sambalpur, 12 de febrero de 2016</p><p>Esta es la última recomendación que les doy, ya que no voy a estar mucho tiempo en esta tierra. Este consejo es para todos. Yo no soy nadie para dar consejos. No lo doy yo, lo da Hariharananda, a través de mi boca:</p><p>Si alguna vez tiene un problema de dinero, concéntrese en el medio del primer centro, hasta que el problema se haya resuelto. Si tiene problemas de sexo, concéntrese en el punto central del segundo chacra. Si tiene problemas digestivos, concéntrese en el centro del tercer chacra. Si tiene problemas emocionales, o padece alguna emoción negativa, mantenga su atención en el punto medio del cuarto chacra. Si tiene una enfermedad de la garganta, o de la tiroides, concéntrese en el medio del quinto chacra. Así mismo, si tiene dificultades de comunicación. Si hay algún problema mental, mantenga la atención en el centro de la pituitaria. Si tiene problemas que atañen diversos órganos, o varios centros, mantenga su atención en la cima de la cabeza.</p><p>En el medio de cada chacra hay un fuerte, una fortaleza inexpugnable. En ese punto central de equilibrio, somos invulnerables. Mantener la atención concentrada ahí, llevará esa armonía a todos los órganos y a los reinos dominados por ese chacra. Para eso, la concentración ahí deberá ser constante, durante la práctica y durante todo el día, todos los días que sea necesario. El fuerte mayor está en la fontanela.</p><p className="jai">¡Jai Gurú!</p></article></div>}
