/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntecedentesRouteImport } from './routes/antecedentes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EmpoderamientoRouteImport } from './routes/empoderamiento'
import { Route as HariharanandaRouteImport } from './routes/hariharananda'
import { Route as LibrosRouteImport } from './routes/libros'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as RaghabanandaRouteImport } from './routes/raghabananda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntecedentesRoute = AntecedentesRouteImport.update({
  id: '/antecedentes',
  path: '/antecedentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpoderamientoRoute = EmpoderamientoRouteImport.update({
  id: '/empoderamiento',
  path: '/empoderamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const HariharanandaRoute = HariharanandaRouteImport.update({
  id: '/hariharananda',
  path: '/hariharananda',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrosRoute = LibrosRouteImport.update({
  id: '/libros',
  path: '/libros',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const RaghabanandaRoute = RaghabanandaRouteImport.update({
  id: '/raghabananda',
  path: '/raghabananda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/contacto': typeof ContactoRoute
  '/empoderamiento': typeof EmpoderamientoRoute
  '/hariharananda': typeof HariharanandaRoute
  '/libros': typeof LibrosRoute
  '/noticias': typeof NoticiasRoute
  '/raghabananda': typeof RaghabanandaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/contacto': typeof ContactoRoute
  '/empoderamiento': typeof EmpoderamientoRoute
  '/hariharananda': typeof HariharanandaRoute
  '/libros': typeof LibrosRoute
  '/noticias': typeof NoticiasRoute
  '/raghabananda': typeof RaghabanandaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/contacto': typeof ContactoRoute
  '/empoderamiento': typeof EmpoderamientoRoute
  '/hariharananda': typeof HariharanandaRoute
  '/libros': typeof LibrosRoute
  '/noticias': typeof NoticiasRoute
  '/raghabananda': typeof RaghabanandaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antecedentes'
    | '/contacto'
    | '/empoderamiento'
    | '/hariharananda'
    | '/libros'
    | '/noticias'
    | '/raghabananda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antecedentes'
    | '/contacto'
    | '/empoderamiento'
    | '/hariharananda'
    | '/libros'
    | '/noticias'
    | '/raghabananda'
  id:
    | '__root__'
    | '/'
    | '/antecedentes'
    | '/contacto'
    | '/empoderamiento'
    | '/hariharananda'
    | '/libros'
    | '/noticias'
    | '/raghabananda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntecedentesRoute: typeof AntecedentesRoute
  ContactoRoute: typeof ContactoRoute
  EmpoderamientoRoute: typeof EmpoderamientoRoute
  HariharanandaRoute: typeof HariharanandaRoute
  LibrosRoute: typeof LibrosRoute
  NoticiasRoute: typeof NoticiasRoute
  RaghabanandaRoute: typeof RaghabanandaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antecedentes': {
      id: '/antecedentes'
      path: '/antecedentes'
      fullPath: '/antecedentes'
      preLoaderRoute: typeof AntecedentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empoderamiento': {
      id: '/empoderamiento'
      path: '/empoderamiento'
      fullPath: '/empoderamiento'
      preLoaderRoute: typeof EmpoderamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hariharananda': {
      id: '/hariharananda'
      path: '/hariharananda'
      fullPath: '/hariharananda'
      preLoaderRoute: typeof HariharanandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libros': {
      id: '/libros'
      path: '/libros'
      fullPath: '/libros'
      preLoaderRoute: typeof LibrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raghabananda': {
      id: '/raghabananda'
      path: '/raghabananda'
      fullPath: '/raghabananda'
      preLoaderRoute: typeof RaghabanandaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntecedentesRoute: AntecedentesRoute,
  ContactoRoute: ContactoRoute,
  EmpoderamientoRoute: EmpoderamientoRoute,
  HariharanandaRoute: HariharanandaRoute,
  LibrosRoute: LibrosRoute,
  NoticiasRoute: NoticiasRoute,
  RaghabanandaRoute: RaghabanandaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
